### PR TITLE
Yunsi/gp 130/implement interaction to gnn

### PR DESCRIPTION
**Pull request by yun-si**
## Change
Only this commit belongs to GP-130
- change embedding return type
- change embedding calling method in model.py
- add api to get interaction detail
- add interaction to model
- change some db column setting and related pg crud functions

## Test
1. pull this branch
2. run
  ```
  docker-compose up -d
  
  docker exec -it graduation-project /bin/bash
  
  uvicorn src.main:app --host localhost --port 7877 --reload
  ```
3. Open Postman
4. click pg_init
5. click http://localhost:7877/embedding_model/0
sample output
  ```
  {
      "2": [
          8,
          11
      ],
      "4": [
          1,
          12
      ],
      "6": [
          1,
          12
      ],
      "8": [
          8,
          11
      ],
      "10": [
          1,
          12
      ]
  }```

### CODE REVIEW

**Review by frafishen — CHANGES_REQUESTED** [review]
The PR didn't pass tests.

```bash
root@ed4cf136bd2b:/srv/graduation-project# pytest
/usr/local/lib/python3.10/site-packages/pytest_asyncio/plugin.py:208: PytestDeprecationWarning: The configuration option "asyncio_default_fixture_loop_scope" is unset.
The event loop scope for asynchronous fixtures will default to the fixture caching scope. Future versions of pytest-asyncio will default the loop scope for asynchronous fixtures to function scope. Set the default fixture loop scope explicitly in order to avoid unexpected behavior in the future. Valid fixture loop scopes are: "function", "class", "module", "package", "session"

  warnings.warn(PytestDeprecationWarning(_DEFAULT_FIXTURE_LOOP_SCOPE_UNSET))
=================================================================================================================================================== test session starts ====================================================================================================================================================
platform linux -- Python 3.10.11, pytest-8.3.2, pluggy-1.5.0
rootdir: /srv/graduation-project
plugins: asyncio-0.24.0, anyio-4.4.0
asyncio: mode=strict, default_loop_scope=None
collected 50 items                                                                                                                                                                                                                                                                                                         

tests/unit/app/test_route.py .......................................F......                                                                                                                                                                                                                                          [ 92%]
tests/unit/services/google_oidc/test_oidc.py ....                                                                                                                                                                                                                                                                    [100%]

========================================================================================================================================================= FAILURES =========================================================================================================================================================
___________________________________________________________________________________________________________________________________________________ test_embedding_model ___________________________________________________________________________________________________________________________________________________

    def test_embedding_model():
        place_dict = {"data": [["臺北市", "士林區"], ["臺北市", "北投區"]]}
>       response_0 = client.post("/embedding_model/0", json=place_dict)

tests/unit/app/test_route.py:286: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/usr/local/lib/python3.10/site-packages/starlette/testclient.py:636: in post
    return super().post(
/usr/local/lib/python3.10/site-packages/httpx/_client.py:1145: in post
    return self.request(
/usr/local/lib/python3.10/site-packages/starlette/testclient.py:519: in request
    return super().request(
/usr/local/lib/python3.10/site-packages/httpx/_client.py:827: in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
/usr/local/lib/python3.10/site-packages/httpx/_client.py:914: in send
    response = self._send_handling_auth(
/usr/local/lib/python3.10/site-packages/httpx/_client.py:942: in _send_handling_auth
    response = self._send_handling_redirects(
/usr/local/lib/python3.10/site-packages/httpx/_client.py:979: in _send_handling_redirects
    response = self._send_single_request(request)
/usr/local/lib/python3.10/site-packages/httpx/_client.py:1015: in _send_single_request
    response = transport.handle_request(request)
/usr/local/lib/python3.10/site-packages/starlette/testclient.py:401: in handle_request
    raise exc
/usr/local/lib/python3.10/site-packages/starlette/testclient.py:398: in handle_request
    portal.call(self.app, scope, receive, send)
/usr/local/lib/python3.10/site-packages/anyio/from_thread.py:287: in call
    return cast(T_Retval, self.start_task_soon(func, *args).result())
/usr/local/lib/python3.10/concurrent/futures/_base.py:458: in result
    return self.__get_result()
/usr/local/lib/python3.10/concurrent/futures/_base.py:403: in __get_result
    raise self._exception
/usr/local/lib/python3.10/site-packages/anyio/from_thread.py:218: in _call_func
    retval = await retval_or_awaitable
/usr/local/lib/python3.10/site-packages/fastapi/applications.py:1054: in __call__
    await super().__call__(scope, receive, send)
/usr/local/lib/python3.10/site-packages/starlette/applications.py:123: in __call__
    await self.middleware_stack(scope, receive, send)
/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py:186: in __call__
    raise exc
/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py:164: in __call__
    await self.app(scope, receive, _send)
/usr/local/lib/python3.10/site-packages/starlette/middleware/cors.py:85: in __call__
    await self.app(scope, receive, send)
/usr/local/lib/python3.10/site-packages/starlette/middleware/sessions.py:85: in __call__
    await self.app(scope, receive, send_wrapper)
/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py:65: in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py:64: in wrapped_app
    raise exc
/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py:53: in wrapped_app
    await app(scope, receive, sender)
/usr/local/lib/python3.10/site-packages/starlette/routing.py:754: in __call__
    await self.middleware_stack(scope, receive, send)
/usr/local/lib/python3.10/site-packages/starlette/routing.py:774: in app
    await route.handle(scope, receive, send)
/usr/local/lib/python3.10/site-packages/starlette/routing.py:295: in handle
    await self.app(scope, receive, send)
/usr/local/lib/python3.10/site-packages/starlette/routing.py:77: in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py:64: in wrapped_app
    raise exc
/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py:53: in wrapped_app
    await app(scope, receive, sender)
/usr/local/lib/python3.10/site-packages/starlette/routing.py:74: in app
    response = await f(request)
/usr/local/lib/python3.10/site-packages/fastapi/routing.py:297: in app
    raw_response = await run_endpoint_function(
/usr/local/lib/python3.10/site-packages/fastapi/routing.py:210: in run_endpoint_function
    return await dependant.call(**values)
src/app/route.py:394: in embeddingModel
    result = await model.run()
src/data_pipeline/model.py:268: in run
    young_user_features, elder_user_features, house_features = self.process_data(
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <src.data_pipeline.model.EmbeddingModel object at 0xffff5bc19810>
df_user = {'message': "Error when embedding user feature: HTTPConnectionPool(host='localhost', port=7877): Max retries exceeded ...ion.HTTPConnection object at 0xffff5bbbf7c0>: Failed to establish a new connection: [Errno 111] Connection refused'))"}
df_house = {'details': 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py"...n embedding user feature: Cannot connect to host localhost:7877 ssl:default [Connect call failed ('127.0.0.1', 7877)]"}

    def process_data(self, df_user, df_house):
>       df_role_0 = df_user[df_user["Role"] == 0]
E       KeyError: 'Role'

src/data_pipeline/model.py:68: KeyError
================================================================================================================================================= short test summary info ==================================================================================================================================================
FAILED tests/unit/app/test_route.py::test_embedding_model - KeyError: 'Role'
```

**Comment by frafishen** [comment]
Is the payload of `http://localhost:7877/embedding_model/0` correct?

image

**Comment by yun-si** [comment]
@frafishen 
try to run `uvicorn src.main:app --host localhost --port 7877 --reload` before running `pytest`
截圖 2024-09-01 下午5 34 50

**Comment by frafishen** [comment]
> @frafishen try to run `uvicorn src.main:app --host localhost --port 7877 --reload` before running `pytest` <img alt="截圖 2024-09-01 下午5 34 50" width="1129" src="https://private-user-images.githubusercontent.com/93365070/363480644-c2794fcb-0ad6-48f2-8858-5e94010f563b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUxODQ0MjUsIm5iZiI6MTcyNTE4NDEyNSwicGF0aCI6Ii85MzM2NTA3MC8zNjM0ODA2NDQtYzI3OTRmY2ItMGFkNi00OGYyLTg4NTgtNWU5NDAxMGY1NjNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAxVDA5NDg0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYzNmZmZDllNDI5ZDU1NzkxNGMzMDlkODQ3ZGRiNTEwMjFhNGJjMmZjODViNmQ4OTRhYWU1ZjExODgwMDJjYzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nXbQ_twAnjAcX9JfPIptvpMpDYigJmdYfea7f8MELZQ">




## Did i miss something?
```bash

╰─ docker exec -it graduation-project /bin/bash

root@737febafc466:/srv/graduation-project# pytest
/usr/local/lib/python3.10/site-packages/pytest_asyncio/plugin.py:208: PytestDeprecationWarning: The configuration option "asyncio_default_fixture_loop_scope" is unset.
The event loop scope for asynchronous fixtures will default to the fixture caching scope. Future versions of pytest-asyncio will default the loop scope for asynchronous fixtures to function scope. Set the default fixture loop scope explicitly in order to avoid unexpected behavior in the future. Valid fixture loop scopes are: "function", "class", "module", "package", "session"

  warnings.warn(PytestDeprecationWarning(_DEFAULT_FIXTURE_LOOP_SCOPE_UNSET))
====================================================================================================================================== test session starts =======================================================================================================================================
platform linux -- Python 3.10.11, pytest-8.3.2, pluggy-1.5.0
rootdir: /srv/graduation-project
plugins: asyncio-0.24.0, anyio-4.4.0
asyncio: mode=strict, default_loop_scope=None
collected 51 items                                                                                                                                                                                                                                                                               

tests/unit/app/test_route.py .......................................F.......                                                                                                                                                                                                               [ 92%]
tests/unit/services/google_oidc/test_oidc.py ....                                                                                                                                                                                                                                          [100%]

============================================================================================================================================ FAILURES ============================================================================================================================================
______________________________________________________________________________________________________________________________________ test_embedding_model ______________________________________________________________________________________________________________________________________

    def test_embedding_model():
        place_dict = {"data": [["臺北市", "士林區"], ["臺北市", "北投區"]]}
>       response_0 = client.post("/embedding_model/0", json=place_dict)

tests/unit/app/test_route.py:286: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/usr/local/lib/python3.10/site-packages/starlette/testclient.py:636: in post
    return super().post(
/usr/local/lib/python3.10/site-packages/httpx/_client.py:1157: in post
    return self.request(
/usr/local/lib/python3.10/site-packages/starlette/testclient.py:519: in request
    return super().request(
/usr/local/lib/python3.10/site-packages/httpx/_client.py:837: in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
/usr/local/lib/python3.10/site-packages/httpx/_client.py:926: in send
    response = self._send_handling_auth(
/usr/local/lib/python3.10/site-packages/httpx/_client.py:954: in _send_handling_auth
    response = self._send_handling_redirects(
/usr/local/lib/python3.10/site-packages/httpx/_client.py:991: in _send_handling_redirects
    response = self._send_single_request(request)
/usr/local/lib/python3.10/site-packages/httpx/_client.py:1027: in _send_single_request
    response = transport.handle_request(request)
/usr/local/lib/python3.10/site-packages/starlette/testclient.py:401: in handle_request
    raise exc
/usr/local/lib/python3.10/site-packages/starlette/testclient.py:398: in handle_request
    portal.call(self.app, scope, receive, send)
/usr/local/lib/python3.10/site-packages/anyio/from_thread.py:287: in call
    return cast(T_Retval, self.start_task_soon(func, *args).result())
/usr/local/lib/python3.10/concurrent/futures/_base.py:458: in result
    return self.__get_result()
/usr/local/lib/python3.10/concurrent/futures/_base.py:403: in __get_result
    raise self._exception
/usr/local/lib/python3.10/site-packages/anyio/from_thread.py:218: in _call_func
    retval = await retval_or_awaitable
/usr/local/lib/python3.10/site-packages/fastapi/applications.py:1054: in __call__
    await super().__call__(scope, receive, send)
/usr/local/lib/python3.10/site-packages/starlette/applications.py:123: in __call__
    await self.middleware_stack(scope, receive, send)
/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py:187: in __call__
    raise exc
/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py:165: in __call__
    await self.app(scope, receive, _send)
/usr/local/lib/python3.10/site-packages/starlette/middleware/cors.py:85: in __call__
    await self.app(scope, receive, send)
/usr/local/lib/python3.10/site-packages/starlette/middleware/sessions.py:85: in __call__
    await self.app(scope, receive, send_wrapper)
/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py:65: in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py:64: in wrapped_app
    raise exc
/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py:53: in wrapped_app
    await app(scope, receive, sender)
/usr/local/lib/python3.10/site-packages/starlette/routing.py:754: in __call__
    await self.middleware_stack(scope, receive, send)
/usr/local/lib/python3.10/site-packages/starlette/routing.py:774: in app
    await route.handle(scope, receive, send)
/usr/local/lib/python3.10/site-packages/starlette/routing.py:295: in handle
    await self.app(scope, receive, send)
/usr/local/lib/python3.10/site-packages/starlette/routing.py:77: in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py:64: in wrapped_app
    raise exc
/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py:53: in wrapped_app
    await app(scope, receive, sender)
/usr/local/lib/python3.10/site-packages/starlette/routing.py:74: in app
    response = await f(request)
/usr/local/lib/python3.10/site-packages/fastapi/routing.py:297: in app
    raw_response = await run_endpoint_function(
/usr/local/lib/python3.10/site-packages/fastapi/routing.py:210: in run_endpoint_function
    return await dependant.call(**values)
src/app/route.py:401: in embeddingModel
    result = await model.run()
src/data_pipeline/model.py:273: in run
    data, reverse_user_id_map, reverse_item_id_map = await self.build_graph(
src/data_pipeline/model.py:200: in build_graph
    plt.savefig(f"src/data_pipeline/graph/{filename}", format="png", dpi=300)
/usr/local/lib/python3.10/site-packages/matplotlib/pyplot.py:1119: in savefig
    res = fig.savefig(*args, **kwargs)  # type: ignore[func-returns-value]
/usr/local/lib/python3.10/site-packages/matplotlib/figure.py:3390: in savefig
    self.canvas.print_figure(fname, **kwargs)
/usr/local/lib/python3.10/site-packages/matplotlib/backend_bases.py:2187: in print_figure
    result = print_method(
/usr/local/lib/python3.10/site-packages/matplotlib/backend_bases.py:2043: in <lambda>
    print_method = functools.wraps(meth)(lambda *args, **kwargs: meth(
/usr/local/lib/python3.10/site-packages/matplotlib/backends/backend_agg.py:497: in print_png
    self._print_pil(filename_or_obj, "png", pil_kwargs, metadata)
/usr/local/lib/python3.10/site-packages/matplotlib/backends/backend_agg.py:446: in _print_pil
    mpl.image.imsave(
/usr/local/lib/python3.10/site-packages/matplotlib/image.py:1656: in imsave
    image.save(fname, **pil_kwargs)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <PIL.Image.Image image mode=RGBA size=2400x1800 at 0xFFFF361AD8D0>, fp = 'src/data_pipeline/graph/graph_visualization_20240901_095100.png', format = 'png', params = {'dpi': (300, 300), 'pnginfo': <PIL.PngImagePlugin.PngInfo object at 0xffff361ad990>}
filename = '/srv/graduation-project/src/data_pipeline/graph/graph_visualization_20240901_095100.png', open_fp = True, save_all = False, filename_ext = '.png', ext = '.png'

    def save(
        self, fp: StrOrBytesPath | IO[bytes], format: str | None = None, **params: Any
    ) -> None:
        """
        Saves this image under the given filename.  If no format is
        specified, the format to use is determined from the filename
        extension, if possible.
    
        Keyword options can be used to provide additional instructions
        to the writer. If a writer doesn't recognise an option, it is
        silently ignored. The available options are described in the
        :doc:`image format documentation
        <../handbook/image-file-formats>` for each writer.
    
        You can use a file object instead of a filename. In this case,
        you must always specify the format. The file object must
        implement the ``seek``, ``tell``, and ``write``
        methods, and be opened in binary mode.
    
        :param fp: A filename (string), os.PathLike object or file object.
        :param format: Optional format override.  If omitted, the
           format to use is determined from the filename extension.
           If a file object was used instead of a filename, this
           parameter should always be used.
        :param params: Extra parameters to the image writer.
        :returns: None
        :exception ValueError: If the output format could not be determined
           from the file name.  Use the format option to solve this.
        :exception OSError: If the file could not be written.  The file
           may have been created, and may contain partial data.
        """
    
        filename: str | bytes = ""
        open_fp = False
        if is_path(fp):
            filename = os.path.realpath(os.fspath(fp))
            open_fp = True
        elif fp == sys.stdout:
            try:
                fp = sys.stdout.buffer
            except AttributeError:
                pass
        if not filename and hasattr(fp, "name") and is_path(fp.name):
            # only set the name for metadata purposes
            filename = os.path.realpath(os.fspath(fp.name))
    
        # may mutate self!
        self._ensure_mutable()
    
        save_all = params.pop("save_all", False)
        self.encoderinfo = params
        self.encoderconfig: tuple[Any, ...] = ()
    
        preinit()
    
        filename_ext = os.path.splitext(filename)[1].lower()
        ext = filename_ext.decode() if isinstance(filename_ext, bytes) else filename_ext
    
        if not format:
            if ext not in EXTENSION:
                init()
            try:
                format = EXTENSION[ext]
            except KeyError as e:
                msg = f"unknown file extension: {ext}"
                raise ValueError(msg) from e
    
        if format.upper() not in SAVE:
            init()
        if save_all:
            save_handler = SAVE_ALL[format.upper()]
        else:
            save_handler = SAVE[format.upper()]
    
        created = False
        if open_fp:
            created = not os.path.exists(filename)
            if params.get("append", False):
                # Open also for reading ("+"), because TIFF save_all
                # writer needs to go back and edit the written data.
                fp = builtins.open(filename, "r+b")
            else:
>               fp = builtins.open(filename, "w+b")
E               FileNotFoundError: [Errno 2] No such file or directory: '/srv/graduation-project/src/data_pipeline/graph/graph_visualization_20240901_095100.png'

/usr/local/lib/python3.10/site-packages/PIL/Image.py:2563: FileNotFoundError
==================================================================================================================================== short test summary info =====================================================================================================================================
FAILED tests/unit/app/test_route.py::test_embedding_model - FileNotFoundError: [Errno 2] No such file or directory: '/srv/graduation-project/src/data_pipeline/graph/graph_visualization_20240901_095100.png'
================================================================================================================================== 1 failed, 50 passed in 5.64s ==================================================================================================================================
```

**Comment by yun-si** [comment]
@frafishen Add folder named graph in data_pipeline and try again.

**Review by frafishen — APPROVED** [review]
LGTM!!

**Pull request merged**
