### PR TITLE
Jenny/gp 46/auto decided whether the env os is window or macos

### PR DESCRIPTION
**Pull request by frafishen**
-  choose the  architecture(amd/arm) from the `.env` file
- key your platform to run the docker in your own `.env` file.
- you can reference the `example.env`

## Test
Rebuild and recompose up the image, and see whether there's a warning sign for the image.

### CODE REVIEW

**Comment by yun-si** [comment]
I put `DOCKER_PLATFORM="linux/arm64"` into the `.env`. But when `docker-compose build` is running, the error message below show, and the building stop.

```
......
352.7 Processing triggers for libc-bin (2.31-13+deb11u6) ...
352.8 qemu: uncaught target signal 11 (Segmentation fault) - core dumped
352.8 Segmentation fault
352.8 qemu: uncaught target signal 11 (Segmentation fault) - core dumped
352.8 Segmentation fault
352.8 dpkg: error processing package libc-bin (--configure):
352.8  installed libc-bin package post-installation script subprocess returned error exit status 139
353.0 Errors were encountered while processing:
353.0  libc-bin
353.2 E: Sub-process /usr/bin/dpkg returned an error code (1)
------
failed to solve: process "/bin/sh -c apt-get install -y postgresql postgresql-contrib python3-pymongo     && rm -rf /var/lib/apt/lists/*" did not complete successfully: exit code: 100
```

Error Line: 

` => ERROR [app  4/14] RUN apt-get install -y postgresql postgresql-contrib python3-pymongo     && rm -rf /var/l  353.3s`

**Comment by frafishen** [comment]
> Error Line:
> 
> ` => ERROR [app 4/14] RUN apt-get install -y postgresql postgresql-contrib python3-pymongo && rm -rf /var/l 353.3s`

@yun-si  I've update the dockerfile, but i still think you can completely delete your previous images, and then rebuild the image.

**Comment by yun-si** [comment]
I have deleted the image, and rebuild it. But when `docker-compose build` is running, the following error message show and the rebuild stop.
```
406.8 debconf: unable to initialize frontend: Dialog
406.8 debconf: (TERM is not set, so the dialog frontend is not usable.)
406.8 debconf: falling back to frontend: Readline
407.5 invoke-rc.d: could not determine current runlevel
407.8 invoke-rc.d: policy-rc.d denied execution of start.
408.0 Setting up libmailutils7:arm64 (1:3.10-3+b1) ...
408.0 Setting up mailutils (1:3.10-3+b1) ...
408.3 update-alternatives: using /usr/bin/frm.mailutils to provide /usr/bin/frm (frm) in auto mode
408.4 update-alternatives: using /usr/bin/from.mailutils to provide /usr/bin/from (from) in auto mode
408.6 update-alternatives: using /usr/bin/messages.mailutils to provide /usr/bin/messages (messages) in auto mode
408.7 update-alternatives: using /usr/bin/movemail.mailutils to provide /usr/bin/movemail (movemail) in auto mode
408.9 update-alternatives: using /usr/bin/readmsg.mailutils to provide /usr/bin/readmsg (readmsg) in auto mode
409.0 update-alternatives: using /usr/bin/dotlock.mailutils to provide /usr/bin/dotlock (dotlock) in auto mode
409.1 update-alternatives: using /usr/bin/mail.mailutils to provide /usr/bin/mailx (mailx) in auto mode
409.1 Processing triggers for libc-bin (2.31-13+deb11u6) ...
409.2 qemu: uncaught target signal 11 (Segmentation fault) - core dumped
409.2 Segmentation fault
409.3 qemu: uncaught target signal 11 (Segmentation fault) - core dumped
409.3 Segmentation fault
409.3 dpkg: error processing package libc-bin (--configure):
409.3  installed libc-bin package post-installation script subprocess returned error exit status 139
409.4 Errors were encountered while processing:
409.4  libc-bin
409.6 E: Sub-process /usr/bin/dpkg returned an error code (1)
------
failed to solve: process "/bin/sh -c apt-get update && apt-get install -y wget unzip postgresql postgresql-contrib python3-pymongo && rm -rf /var/lib/apt/lists/*" did not complete successfully: exit code: 100
```

**Comment by yun-si** [comment]
It is fine when I run `docker-compose build`. But when `docker-compose up -d` is running, the following error message show.
```
C:\Users\cherr\大學專案\0_畢專\Graduation-Project>docker-compose up -d
[+] Running 41/3
 ✔ postgres_db 14 layers [⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿]      0B/0B      Pulled                                                  39.6s
 ✔ mongodb 8 layers [⣿⣿⣿⣿⣿⣿⣿⣿]      0B/0B      Pulled                                                             53.5s
 ✔ pgadmin 16 layers [⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿]      0B/0B      Pulled                                                    52.4s
[+] Running 3/5
 - Network graduation-project_default  Created                                                                    11.8s
 ✔ Container postgres-db               Started                                                                     9.8s
 - Container graduation-project        Starting                                                                   11.7s
 ✔ Container pgadmin4                  Started                                                                     9.7s
 ✔ Container mongodb                   Started                                                                     9.5s
Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "uvicorn": executable file not found in $PATH: unknown
```

I have run `docker container prune` to delete the previous container, but this still happen.
I even try to delete all the container and image, reopen my computer, but none of them worked.
image

However uvicorn is in requirements.txt, and DockerFile did have
```
# Set up Python environment
COPY ./requirements.txt ./
RUN pip install -r requirements.txt
```

I don't know why the error happen

**Comment by yun-si** [comment]
I can successfully build the container, however when I run `docker-compose up -d`, the message below show.
```
...Graduation-Project>docker-compose up -d
time="2024-04-30T12:00:04+08:00" level=warning msg="C:\\Users\\cherr\\大學專案\\0_畢專\\Graduation-Project\\docker-compose.yml: `version` is obsolete"
[+] Running 3/4
 ✔ Container pgadmin4            Started                                                                           0.0s
 ✔ Container mongodb             Started                                                                           0.0s
 ✔ Container postgres-db         Started                                                                           0.0s
 - Container graduation-project  Starting                                                                          1.1s
Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "uvicorn": executable file not found in $PATH: unknown
```

All the other container go well (I have tried to open pgadmin4, and it can be opened), but this container `graduation-project` fail to start.

**Pull request closed without merging**
