### PR TITLE
Esther/gp 67/api for updating profile page

### PR DESCRIPTION
**Pull request by Esther125**
- Follow the steps in doc-03 to launch API service locally.
- Use the postman examples I provided in the group to test the update endpoint.
螢幕擷取畫面 2024-09-11 200732

### CODE REVIEW

**Comment by frafishen** [comment]
you should remove this file, `.github/workflows/my_workflow.yml`, or the "checks" would always be failed

**Review by frafishen — CHANGES_REQUESTED** [review]
the conflicts need to be fixed~
and I forgot which apis need to tested with postman?

**Comment by Esther125** [comment]
@frafishen I have posted the postman example file to the group chat. You need to test the two apis that start with update.

**Review by frafishen — APPROVED** [review]
LGTM!!!

**Pull request merged**
