### PR TITLE
Yunsi/gp 115/improve gnn

### PR DESCRIPTION
**Pull request by yun-si**
## New Change
- fix test_item_embedding bug
- embedding_model test cannot be done in Github Action. But pytest can pass at localhost. So I comment test_embedding_model function when commit. The reason is as below.

> Because in GitHub Actions, host names such as host.docker.internal cannot be resolved directly because this is a special host name inside the Docker container and is only valid in the local Docker environment.

ToDo: (Next ticket)
1. Create db table for interaction (pg_init.py)
2. Write API to access related interaction data (pg_CRUD.py)
3. request API to access data (this file)
4. ID mapping

## Changes
1. Transform model to a class and API (embeddingModel)
2. Add place selection to model
    - Add optional place condition to get_house_info api function
    - Edit item_embedding api function
 
## Test
1. pull this branch
2. Run `docker-compose build`
3. Run `docker-compose up -d`
4. DB init: click http://localhost:7877/pg_init/
5. Test (Use Postman)
  GET http://localhost:7877/embedding_model/0
  put the following to the request body
  ```
    {
        "data": [["臺北市", "士林區"], ["臺北市", "北投區"]]
    }
  ```
or access [the postman link](https://galactic-station-885342.postman.co/workspace/My-Workspace~646f4f2f-a6af-4321-89de-3c723e587c7c/request/32563015-86b5f6fd-498f-4689-9d22-1896a4bc7171?action=share&creator=32563015&ctx=documentation)
  you will get

  People_ID: [House_ID, House_ID]

  ```
  {
      "2": [
          5,
          9
      ],
      "4": [
          8,
          11
      ],
      "6": [
          6,
          9
      ],
      "8": [
          8,
          11
      ],
      "10": [
          11,
          8
      ]
  }
  ```
  
  You can also let the data list be empty, it means that you put all the houses into the model.
  ```
    {
        "data": []
    }
  ```

✨Remind: because interaction data is fix now, so if you want to select place, ["臺北市", "士林區"] must be included.

### CODE REVIEW

**Comment by yun-si** [comment]
@yun-si  Fix bug

**Comment by yun-si** [comment]
@Esther125 @DanielYang1209 @Jeaninetang @frafishen 
I have fix the bug, help me check the pr/

**Comment by frafishen** [comment]
i'm not really sure, but i have to change this [line](https://github.com/Fang-4-Group/Graduation-Project/blob/a63c6b552dcce55c05ad9cb9cf93b759b9d824eb/database/migrations/mongodb_init.py#L14) to 
```python
self.url = os.getenv("MONGO_DB_URI")
```
and the unit test for `test_mongodb_init()` could be passed

**Comment by frafishen** [comment]
there's no data here?
image

**Comment by yun-si** [comment]
> i'm not really sure, but i have to change this [line](https://github.com/Fang-4-Group/Graduation-Project/blob/a63c6b552dcce55c05ad9cb9cf93b759b9d824eb/database/migrations/mongodb_init.py#L14) to
> 
> ```python
> self.url = os.getenv("MONGO_DB_URI")
> ```
> 
> and the unit test for `test_mongodb_init()` could be passed

In the next pr, I have changed this line.
But I am not sure why the test of this pr can pass while I do not change this line.

**Comment by yun-si** [comment]
> there's no data here? image

sorry... I forgot that I have changed the routing path.

**Comment by yun-si** [comment]
https://www.postman.com/galactic-station-885342/workspace/my-workspace/collection/32563015-41b91a83-3b17-40ea-9e77-4ed038a9085c?action=share&creator=32563015

I made the postman to public, everyone can access it.

**Comment by frafishen** [comment]
are these two APIs have to be tested? 

image

**Comment by frafishen** [comment]
the other APIs are LGTM!!

**Review by frafishen — APPROVED** [review]
LGTM!!!!

**Pull request merged**
