### PR TITLE
Refactor DB files

### PR DESCRIPTION
**Pull request by yun-si**
1. Add database Folder and seeds, migrations folders in.
2. Move DB testing file to seeds folder.

I'am not sure whether I complete the refactor work or not so that I need someone to check whether I am on the right way.

### CODE REVIEW

**Comment by frafishen** [comment]
There's a piece of code like this in your PR.
```python
@router.get("/test_create/")
async def test_create():
    conn = await access_db()
    try:
        cursor = conn.cursor()
        # 建立測試資料表&資料
        cursor.execute(
            """CREATE TABLE test_table (id serial PRIMARY KEY,
                    name VARCHAR(255), age INTEGER);
                    INSERT INTO test_table (name, age) VALUES ('Alice', 25);
                    INSERT INTO test_table (name, age) VALUES ('Bob', 30);
                    INSERT INTO test_table (name, age) VALUES ('Charlie', 28);
                    """
        )
        conn.commit()
        return {"message": "success to create table"}
    except Exception as e:
        error_msg = "Error selecting data: " + str(e)
        raise HTTPException(status_code=500, detail=error_msg)  # noqa
    finally:
        conn.close()
```

The code snippet provided illustrates the separation between the application's layers, such as the database (DB) layer, and the routing layer, as detailed below.


```python
# in the ./src/app/route.py

from database.seeds.initialization import create_table
@router.get("/test_create/")
async def test_create():
    result = await create_table()
    if result is None:
        content = {"message": "database not connected."}
    else:
        content = {"message": "success to create table"}
    return content
        

# in the ./database/seeds/initialization.py

def create_table():
    conn = await access_db()
    try:
        cursor = conn.cursor()
        # 建立測試資料表&資料
        cursor.execute(
            """CREATE TABLE test_table (id serial PRIMARY KEY,
                    name VARCHAR(255), age INTEGER);
                    INSERT INTO test_table (name, age) VALUES ('Alice', 25);
                    INSERT INTO test_table (name, age) VALUES ('Bob', 30);
                    INSERT INTO test_table (name, age) VALUES ('Charlie', 28);
                    """
        )
        conn.commit()
        return {"message": "success to create table"}
    except Exception as e:
        error_msg = "Error selecting data: " + str(e)
        raise HTTPException(status_code=500, detail=error_msg)  # noqa
    finally:
        conn.close()
```

**Comment by yun-si** [comment]
I have update the content and structure. The testing step is as below

1. pull this branch
2. run `docker-compose up -d`
3. open Postgresql
4. run GET http://localhost:7877/test_create/
5. get {"status": 200, "message": "success to create table"} means you make it.
6. you can also test GET http://localhost:7877/test_select/
7. if the status in return is 200, you make it.

@frafishen @Esther125 @DanielYang1209 @Jeaninetang 
I am not sure whether the comment will send mail to you, so I mention you here🐳
Please help me check the structure and test it 🐻‍❄️

**Comment by frafishen** [comment]
@yun-si 
I get the 500 error. Maybe we can discuss it tomorrow!
image

**Comment by yun-si** [comment]
Because the test_table has alrealdy exist in you db, so that when you call test_create it may trigger Exception.
You can try other api such as test_select and test_drop, or you can try test_drop first to drop the table, and then try test_create again.

**Comment by yun-si** [comment]
> @yun-si **I get the 500 error. Maybe we can discuss it tomorrow!**

Because the test_table has alrealdy exist in your db, so that when you call test_create it may trigger Exception.
You can try other api such as test_select and test_drop, or you can try test_drop first to drop the table, and then try test_create again.

**Pull request merged**
