### PR TITLE
Jenny/gp 34/seperate the credential of the db out of the original program

### PR DESCRIPTION
**Pull request by frafishen**
- move the credential to the .env
    - you can go to the readme file to refresh the `.env` file.
- refactor the code of `database/seeds/mongo_api_for_testing.py` and `database/seeds/pg_api_for_testing.py` to make the code more OOP style.
- update the `docker-compose.yml` and the other files that are influenced by the refactoring.

## The way to review
No new feature is added, so just test everything in the `readme` is ok.

### CODE REVIEW

**Comment by yun-si** [comment]
I have run `docker-compose build` again. But when I am testing, I got the problems below.

1. When I run `docker-compose up -d`, I got the warning message.
```
time="2024-04-24T21:44:56+08:00" level=warning msg="The \"PGADMIN_DEFAULT_PASSWORD\" variable is not set. Defaulting to a blank string."
time="2024-04-24T21:44:57+08:00" level=warning msg="The \"POSTGRES_USER\" variable is not set. Defaulting to a blank string."
time="2024-04-24T21:44:57+08:00" level=warning msg="The \"POSTGRES_PASSWORD\" variable is not set. Defaulting to a blank string."
time="2024-04-24T21:44:57+08:00" level=warning msg="The \"POSTGRES_DB\" variable is not set. Defaulting to a blank string."
time="2024-04-24T21:44:57+08:00" level=warning msg="The \"PGADMIN_DEFAULT_EMAIL\" variable is not set. Defaulting to a blank string."
time="2024-04-24T21:44:57+08:00" level=warning msg="The \"POSTGRES_USER\" variable is not set. Defaulting to a blank string."
time="2024-04-24T21:44:57+08:00" level=warning msg="The \"POSTGRES_PASSWORD\" variable is not set. Defaulting to a blank string."
time="2024-04-24T21:44:57+08:00" level=warning msg="The \"POSTGRES_DB\" variable is not set. Defaulting to a blank string."
time="2024-04-24T21:44:57+08:00" level=warning msg="The \"PGADMIN_DEFAULT_EMAIL\" variable is not set. Defaulting to a blank string."
time="2024-04-24T21:44:57+08:00" level=warning msg="The \"PGADMIN_DEFAULT_PASSWORD\" variable is not set. Defaulting to a blank string."

[+] Running 4/4
 ✔ Container pgadmin4            Running                                                                           0.0s
 ✔ Container postgres-db         Running                                                                           0.0s
 ✔ Container mongodb             Running                                                                           0.0s
 ✔ Container graduation-project  Started                                                                          14.1s
```

2. When I am testing http://localhost:7877/test_create/, I got an Internal Server Error.
image


3. When I test http://localhost:7877/test_insert_mongo/, I got an error just as the picture below show.
image

```
{"detail":"Other error when inserting data: localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms), Timeout: 30s, Topology Description: <TopologyDescription id: 662910a69e69a05a189e1e14, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>"}
```

Do I miss some steps to test?

**Comment by frafishen** [comment]
> I have run `docker-compose build` again. But when I am testing, I got the problems below.
> 
> 1. When I run `docker-compose up -d`, I got the warning message.
> 
> ```
> time="2024-04-24T21:44:56+08:00" level=warning msg="The \"PGADMIN_DEFAULT_PASSWORD\" variable is not set. Defaulting to a blank string."
> time="2024-04-24T21:44:57+08:00" level=warning msg="The \"POSTGRES_USER\" variable is not set. Defaulting to a blank string."
> time="2024-04-24T21:44:57+08:00" level=warning msg="The \"POSTGRES_PASSWORD\" variable is not set. Defaulting to a blank string."
> time="2024-04-24T21:44:57+08:00" level=warning msg="The \"POSTGRES_DB\" variable is not set. Defaulting to a blank string."
> time="2024-04-24T21:44:57+08:00" level=warning msg="The \"PGADMIN_DEFAULT_EMAIL\" variable is not set. Defaulting to a blank string."
> time="2024-04-24T21:44:57+08:00" level=warning msg="The \"POSTGRES_USER\" variable is not set. Defaulting to a blank string."
> time="2024-04-24T21:44:57+08:00" level=warning msg="The \"POSTGRES_PASSWORD\" variable is not set. Defaulting to a blank string."
> time="2024-04-24T21:44:57+08:00" level=warning msg="The \"POSTGRES_DB\" variable is not set. Defaulting to a blank string."
> time="2024-04-24T21:44:57+08:00" level=warning msg="The \"PGADMIN_DEFAULT_EMAIL\" variable is not set. Defaulting to a blank string."
> time="2024-04-24T21:44:57+08:00" level=warning msg="The \"PGADMIN_DEFAULT_PASSWORD\" variable is not set. Defaulting to a blank string."
> 
> [+] Running 4/4
>  ✔ Container pgadmin4            Running                                                                           0.0s
>  ✔ Container postgres-db         Running                                                                           0.0s
>  ✔ Container mongodb             Running                                                                           0.0s
>  ✔ Container graduation-project  Started                                                                          14.1s
> ```
> 
> 2. When I am testing http://localhost:7877/test_create/, I got an Internal Server Error.
> 
> image
> 3. When I test http://localhost:7877/test_insert_mongo/, I got an error just as the picture below show.
> 
> image
> ```
> {"detail":"Other error when inserting data: localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms), Timeout: 30s, Topology Description: <TopologyDescription id: 662910a69e69a05a189e1e14, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>"}
> ```
> 
> Do I miss some steps to test?

@yun-si 
You would need to check to this branch to read the Readme doc. 
I add the example.env file into the `root`.
Just copy the content in the `example.env`, and paste to your `.env` file, which originally stores your Line tokens.
https://github.com/Fang-4-Group/Graduation-Project/blob/jenny/GP-34/Seperate-the-Credential-of-the-DB-out-of-the-original-program/example.env

**Comment by yun-si** [comment]
The db part is all right except test_select_mongo api.

image

Your code loss the transformation for data accessing from mongoDB, so that when testing http://localhost:7877/test_select_mongo/, Internal Server Error occur.

All the other is fine.

**Comment by frafishen** [comment]
@yun-si Actually, the original code could be run well at my localhost.
I still adjust the code with your way of transforming the data.
Could it run well on your side?

**Comment by yun-si** [comment]
> @yun-si Actually, the original code could be run well at my localhost. I still adjusted the code with your way of transforming the data. Could it run well on your side?

It is fine after the transformation was added. But our environment is the same. Why this happens?

The error message of mine is about fastapi json format.

**Review by yun-si — APPROVED** [review]

**Comment by frafishen** [comment]
do you totally delete the PostgreSQL container, image, and volume, before build up the new image?
i think it might have some impact!

**Pull request merged**
