### PR TITLE
[GP-101]Add hints for the first page

### PR DESCRIPTION
**Pull request by Jeaninetang**
**Check:**

There's a hint on :

- Sleep time
- Drink
- Smoke
- Clean
It should be showed like below
image

- House size(old people)
It should be showed like below
image

### CODE REVIEW

**Comment by yun-si** [comment]
I think drink and smoke need to have an option 0 meaning no drink or no smoke

**Comment by yun-si** [comment]
The textfield can be change to another format:
https://element-plus.org/en-US/component/overview.html

**Review by yun-si — APPROVED** [review]
I recommend that 飲酒程度 can be changed to 飲酒頻率, and provides like 4 or 5 choices for example 不喝，很少，偶爾...... in next ticket. 抽菸程度 can be improved too.

**Review by frafishen — APPROVED** [review]
LGTM!!!

**Pull request merged**
