### PR TITLE
[GP-122] Add column and edit insert data

### PR DESCRIPTION
**Pull request by yun-si**
## Changes
- Add two column(Line_ID, Mail) in PEOPLE table
- Add sample data

## Test
1. run `docker-compose up -d`
2. click http://localhost:7877/pg_init/
3. click http://localhost:7877/get_young_info/?amount=3
if success you will see Line_ID and Mail in response
截圖 2024-07-27 下午1 46 24

### CODE REVIEW

**Comment by yun-si** [comment]
I am considering whether to change the name to User_ID, or its ok to use different name from chat record.

**Comment by yun-si** [comment]
在之後的api備註

**Comment by yun-si** [comment]
already remove the workflow file
imag

@Esther125 @DanielYang1209 @Jeaninetang @frafishen
help me check, thanks

**Review by frafishen — APPROVED** [review]
LGTM!

**Pull request merged**
