### PR TITLE
esther/GP-28/linebot-programming

### PR DESCRIPTION
**Pull request by Esther125**
# Prerequisites
- Create your [LINE Developers Account](https://account.line.biz/login?redirectUri=https%3A%2F%2Fdevelopers.line.biz%2Fconsole%2Fchannel%2Fnew%3Ftype%3Dline-login) and ask me to add you to roles.
- Download [ngrok](https://ngrok.com/download) and register an account to get your auth token.
- Add this official account as a friend.
<div align="center">
  
</div>

# Test 
```powershell
# Switch to my branch
git checkout esther/GP-28/linebot-programming

git pull

# Move to chatbot directory
cd .\src\chatbot
```
Add an `.env` file and add the settings below. You can get these variables in LINE Developers Account's Settings.
```env
CHANNEL_SECRET=[YOUR_CHANNEL_SECRET]
CHANNEL_ACCESS_TOKEN=[YOUR_CHANNEL_ACCESS_TOKEN]
```
Upzip the ngrok zip file and add the directory to .\src\chatbot
```python
# Start the server
# Run this command in root
uvicorn src.chatbot.main:app --host localhost --port 8080  --reload
```
The app will run on port 8080.

## ngrok
execute `ngrok.exe` (It's in the directory you just unzipped)
```powershell
# Set up your ngrok account authentication token
ngrok authtoken [YOUR_AUTH_TOKEN] 

# Save your ngrok authentication token
ngrok config add-authtoken [YOUR_AUTH_TOKEN] 

# Expose port 8080 
ngrok http 8080
```
Copy the Forwarding url value (It is supposed to look like: https://xxxxxx.ngrok-free.app) and send the url to me. I will help you update to Dialog's webhook url.

# Result expected
If you run the server correctly, the message you get in the chat room will always have "( 我有經過 FastAPI Server )" as a suffix.
<div align="center">
  result
</div>

### CODE REVIEW

**Comment by frafishen** [comment]
My Developer Account: x0180368905@gmail.com
Pls add me into the roles.

**Comment by frafishen** [comment]
The requirement.txt would be re-installed when you have the command, `docker-compose build`, again.

**Comment by frafishen** [comment]
Where should the `.env` be placed? under the root or the folder, chatbot?

**Comment by Esther125** [comment]
You already cd to the chatbot directory, so you are supposed to put your `.env` file there.

**Review by frafishen — CHANGES_REQUESTED** [review]

**Review by frafishen — APPROVED** [review]

**Review by frafishen — CHANGES_REQUESTED** [review]
wait! the readme should be updated!!

**Review by frafishen — APPROVED** [review]

**Pull request merged**
